[project]
name = 'Decentralized-Art-Authentication-and-Provenance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.artwork-registration]
path = 'contracts/artwork-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.exhibition-loan]
path = 'contracts/exhibition-loan.clar'
clarity_version = 2
epoch = 2.5

[contracts.forgery-detection]
path = 'contracts/forgery-detection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
